### ISSUE TITLE
On the corpparty detail page, add filing full_desc

### ISSUE THREAD

**Issue by countable** [bcgov/sbc-search#107] opened 2020-03-10 23:55 UTC
SELECT B.FULL_DESC
FROM FILING        A
    ,FILING_TYPE   B
WHERE A.FILING_TYP_CD = B.FILING_TYP_CD
AND EVENT_ID = 15592089

**Comment by syin** [comment] 2020-03-20 02:18
duplicate of https://github.com/bcgov/sbc-search/issues/105

**Closed by syin** 2020-03-20 02:18 UTC
